### ISSUE TITLE
CI/DI: Add code to automatiically update Docker Images for Manager and Processor 

### ISSUE THREAD

**Issue by eranra** [observ-vol-mgt/observ-vol-mgt#94]
Based on a similar approch from the controller:
1. add to GitHub actions like here: https://github.com/observ-vol-mgt/observ-vol-mgt/blob/main/.github/workflows/push.yml#L31 
2. add relevant step in manager and processors make files like here: https://github.com/observ-vol-mgt/observ-vol-mgt/blob/main/controller/Makefile#L68
3. and specific 
https://github.com/observ-vol-mgt/observ-vol-mgt/blob/main/controller/Makefile#L20
https://github.com/observ-vol-mgt/observ-vol-mgt/blob/main/controller/Makefile#L25

**Comment by seepgoel** [comment]
@eranra has the controller Makefile been updated since you added these instructions in the issue. I was looking at this and noticed you point to Line no 68 in that file, whereas the version I see has only 42 line. 
I think I follow the approach you have outlined though, was just curious what you were pointing to.

**Comment by eranra** [comment]
@seepgoel yes :-( --- I moved some of the functionality to a `.mk` folder to make things more organized. Maybe you can look for the Makefile from last week when I made that comment ( the relevant Makefile targets moved now to the ci.mk and development.mk files )
